### ISSUE TITLE
BLE Support

### ISSUE THREAD

**Issue by akash-patel** [NordicSemiconductor/pc-nrf-dfu-js#58]
Seems like this project is intended for serial DFU over USB only, correct? The about section of this repository mentions "Javascript implementation of Nordic's DFU protocol, over serial **or BLE**."

For BLE support, is it best to consult nrfutil? https://github.com/NordicSemiconductor/pc-nrfutil

**Comment by bencefr** [comment]
Depending on your language of choice. For python pc-nrfutil is the way to go, for javascript there's a BLE DFU implementation in pc-ble-driver-js https://github.com/NordicSemiconductor/pc-ble-driver-js/blob/master/examples/dfu.js.

The BLE DFU in this repository was implemented for Noble (https://github.com/noble/noble), but it's neither tested, nor supported.
